"""change class name of UsersFriends to UsersFriend

Revision ID: 0ef2b1c5ceba
Revises: de49d0734dd7
Create Date: 2020-06-21 20:48:35.888939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef2b1c5ceba'
down_revision = 'de49d0734dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_friends', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_friends_users_id_fkey', 'users_friends', type_='foreignkey')
    op.create_foreign_key(None, 'users_friends', 'users', ['user_id'], ['id'])
    op.drop_column('users_friends', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_friends', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users_friends', type_='foreignkey')
    op.create_foreign_key('users_friends_users_id_fkey', 'users_friends', 'users', ['users_id'], ['id'])
    op.drop_column('users_friends', 'user_id')
    # ### end Alembic commands ###
