"""added group_users join table

Revision ID: 829a53e2e76e
Revises: 1e52174a21e4
Create Date: 2020-06-21 14:23:08.038115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829a53e2e76e'
down_revision = '1e52174a21e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_users')
    # ### end Alembic commands ###
