"""removed comments from transactions

Revision ID: 8ea8e08a1b1c
Revises: a33407f3f5b1
Create Date: 2020-06-24 08:36:03.442155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea8e08a1b1c'
down_revision = 'a33407f3f5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_transaction_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_transaction_id_fkey', 'comments', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
