"""added relationship between users and expenses

Revision ID: a1448928a54f
Revises: bfa080d24947
Create Date: 2020-06-21 13:24:28.671737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1448928a54f'
down_revision = 'bfa080d24947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
