"""added comments to expenses

Revision ID: bd7f7b2fd770
Revises: 8ea8e08a1b1c
Create Date: 2020-06-24 08:45:57.054546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7f7b2fd770'
down_revision = '8ea8e08a1b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('expense_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'expense_id')
    # ### end Alembic commands ###
