"""added updated_at to transactions expenses and friendships

Revision ID: ed563809116c
Revises: bd7f7b2fd770
Create Date: 2020-06-27 11:39:54.273268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed563809116c'
down_revision = 'bd7f7b2fd770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('friendships', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    op.drop_column('friendships', 'updated_at')
    op.drop_column('expenses', 'updated_at')
    # ### end Alembic commands ###
